### ISSUE TITLE
Question on key algorithms used

### ISSUE THREAD

**Issue by arijit79** [brndnmtthws/dryoc#1]
So just a few questions regarding the algorithms. What key algorithms are being used when encrypting/decrypting data and signing/verifying it

**Comment by brndnmtthws** [comment]
For public-key encryption, it's based on X25519 (i.e., Diffie-Hellman on elliptic curve 25519).

The secret-key based stuff can use any randomly generated key.

For the most part, everything matches that of the libsodium implementation.

**Comment by arijit79** [comment]
Thanks. It would be great if you just write about it in the docs. Anyways thanks again

**Comment by brndnmtthws** [comment]
There are some mentions in the docs already. Where specifically are you looking? I can add some more detail if you can indicate where it's missing from.

**Comment by arijit79** [comment]
I think you should probably add something in `keypair` module. That should probably do it
