### ISSUE TITLE
[Bug]: Trivially Unsound code (out of bounds memory access)

### ISSUE THREAD

**Issue by jnhev42** [brndnmtthws/dryoc#23]
### What happened?

This code:
```rs
impl<const LENGTH: usize> ByteArray<LENGTH> for Vec<u8> {
    #[inline]
    fn as_array(&self) -> &[u8; LENGTH] {
        let arr = self.as_ptr() as *const [u8; LENGTH];
        unsafe { &*arr }
    }
}
```
will cast Vec's of a size below LENGTH to an array of LENGTH, leading to out-of-bounds reads
[source link](https://docs.rs/dryoc/latest/src/dryoc/types.rs.html#150)

### Version

0.4.0

### Which OS are you seeing the problem on?

Linux

### Test code

```Rust
`vec![1, 2].as_array()[2]` <- out of bounds read.
```

**Comment by brndnmtthws** [comment]
As a general rule, casting a vec to an array is not a great thing, but it can be convenient. Most of the critical bits use fixed-length arrays (keys, nonces, etc) so while this is indeed a bug, I wouldn't consider it critical.

In any case, thanks for reporting it. I've added an assertion which will trigger an error in both debug and release mode.

**Comment by jnhev42** [comment]
Also there's an identical issue for the `&mut` version of this
